name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build firmware binary
      working-directory: mt-fw
      run: cargo build --verbose
    - name: Install udev tools
      run: sudo apt-get install -y libudev-dev
    - name: Build relay driver
      working-directory: mt-relay
      run: cargo build --verbose
